//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDictionary.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int AnswerID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual QuestionAnswer QuestionAnswer { get; set; }
        public virtual QuestionCategory QuestionCategory { get; set; }
    }
}
