//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDictionary.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synonym
    {
        public int Id { get; set; }
        public int FirstSynonymID { get; set; }
        public int SecondSynonymID { get; set; }
    
        public virtual Word Word { get; set; }
        public virtual Word Word1 { get; set; }
    }
}
